aiai_cookie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>', views.cart_add, name='add'),
    path('remove/<int:product_id>', views.cart_remove, name='remove'),
    path('checkout/', views.checkout_page, name='checkout'),
    path('pdf/views/<int:order_id>/', views.cart_pdf_view, name='pdf'),
    path('pdf/<int:order_id>/', views.generate_order_pdf, name='generate_pdf'),
    path('', views.cartpage, name='cartpage'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    # path('', views.homepage, name='homepage'),
    path('', views.list_product_view, name='homepage'),
    path('product/<slug:slug>/', views.product_detail, name='product')
]

cart/models.py
from django.db import models
from account.models import Profile


# Create your models here.
class OrderModel(models.Model):
    order_id = models.BigAutoField(primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    start = models.DateField()
    end = models.DateField()
    total_price = models.DecimalField(max_digits=10,
                                      decimal_places=2)
    delivered = models.BooleanField(default=False)

    def __str__(self):
        return f"{sum([item.quantity for item in self.orderitem_set.all()])} item with RM {self.total_price}"

    def __iter__(self):
        for item in self.orderitem_set.all():
            yield item


class OrderItem(models.Model):
    product = models.CharField(max_length=200)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    total_price = models.DecimalField(max_digits=10,
                                      decimal_places=2)
    order = models.ForeignKey(OrderModel, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product} x {self.quantity}"

cart/forms.py
from datetime import date
from django import forms
from django.core.exceptions import ValidationError


class CartForm(forms.Form):
    start = forms.DateField()
    end = forms.DateField()

    # todo: looks like is for models, step to get it is through Profile._meta.fields[4].clean function
    # to_python -> validate -> clean_<field> -> clean
    # to_python: Take raw value turn into python obj (str)
    # validate: fields-specific validation on the data
    # clearn_<field>: place that we can customize our validate function
    # clearn: addition clean that needs to be done on the form as a whole

    # Form
    # full_clean -> _clean_fields, _clean_form, _post_clean
    # _clean_fields: called all clean_<field>
    # _clean_form: get cleaned_data
    # _post_clean: for Model
    def clean_start(self):
        value = self.cleaned_data['start']
        if value < date.today():
            # Ensure date is today or later
            raise ValidationError("How can we delivery it before today ?")

        # Change format to YYYY-MM-DD
        return value.strftime("%Y-%m-%d")

    def clean_end(self):
        value = self.cleaned_data['end']
        return value.strftime("%Y-%m-%d")

cart/views.py
import weasyprint
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.shortcuts import render, redirect, HttpResponse
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from shop.forms import CartAddProductForm
from .cart import Cart
from .forms import CartForm
from .models import OrderModel, OrderItem


# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(str(product_id), int(cd['quantity']))
    return redirect('cart:cartpage')
    # return redirect('shop:homepage')
    # return render(request, 'base.html', context={})


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    cart.remove(str(product_id))
    return redirect('cart:cartpage')


@login_required(login_url=reverse_lazy('account:login'))
def cartpage(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html', context={'cart':cart})


@require_POST
def checkout_page(request):
    # 1. get total order
    # 2. get pickup date
    # 3. saved into db
    # 4. generate pdf
    # 5. clear existing cart items
    # 6. download pdf
    # 7. redirect to whatsapp
    cart = Cart(request)
    form = CartForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        order = OrderModel(start=cd['start'],
                           end=cd['end'],
                           total_price=cart.total_price)
        order.save()
        for item in cart:
            OrderItem.objects.create(product=item['name'],
                                     quantity=item['quantity'],
                                     price=item['price'],
                                     total_price=item['total_price'],
                                     order=order)
        cart.clear()
        return redirect('shop:homepage')

    return redirect('cart:cartpage')


def generate_order_pdf(request, order_id):
    order = OrderModel.objects.get(order_id=order_id)
    html = render_to_string('cart/order_pdf.html',
                            {'order': order},
                            request)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f"filename=order_{order_id}.pdf"
    weasyprint.HTML(string=html,
                    base_url=request.build_absolute_uri()).write_pdf(response,
                                           stylesheets=[
                                               weasyprint.CSS(
                                                   settings.STATIC_ROOT / 'css/pdf.css'
                                               )
                                           ])

    return response


@login_required(login_url=reverse_lazy('account:login'))
def cart_pdf_view(request, order_id):
    order = OrderModel.objects.get(order_id=order_id)
    return render(request, 'cart/order_pdf.html', {'order':order})

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" />
{% endblock %}
{% block content %}
  <div class="container mx-auto mt-10">
    <div class="md:flex shadow-md my-10">
        <div class="md:w-3/4 bg-white px-10 py-10">
            <div class="flex justify-between">
              <h1 class="font-semibold text-2xl">Shopping Cart</h1>
              <h2 class="font-semibold text-2xl">{{ cart.total_item }} Items</h2>
            </div>
            <div class="flex mt-10 mb-5">
                  <h3 class="font-semibold text-gray-600 md:text-base text-xs uppercase w-2/5">Product Details</h3>
                  <h3 class="font-semibold text-center text-gray-600 md:text-base text-xs uppercase w-1/5 text-center">Quantity</h3>
                  <h3 class="font-semibold text-center text-gray-600 md:text-base text-xs uppercase w-1/5 text-center">Price</h3>
                  <h3 class="font-semibold text-center text-gray-600 md:text-base text-xs uppercase w-1/5 text-center">Total</h3>
            </div>
            <!--Order List -->
            {% for p in cart %}
                <div class="flex items-center hover:bg-gray-100 -mx-8 px-6 py-5">
                    <div class="flex w-2/5"> <!-- product -->
                        <div class="w-20">
<!--                        <img class="h-24" src="https://drive.google.com/uc?id=18KkAVkGFvaGNqPy2DIvTqmUH_nk39o3z" alt="">-->
                            <img class="h-24" src="{{ p.image }}" alt="">
                        </div>
                    <div class="flex flex-col justify-between ml-4 flex-grow">
                        <span class="font-bold text-sm">{{ p.name }}</span>
                        <form id='remove' action="{% url 'cart:remove' p.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" value="remove">
                            <a href="#" onclick="document.getElementById('remove').submit();" class="font-semibold hover:text-red-500 text-gray-500 text-xs">Remove</a>
                        </form>

                    </div>
                </div>
                <div class="flex justify-center w-1/5">
                    <svg class="fill-current text-gray-600 w-3" viewBox="0 0 448 512"><path d="M416 208H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"/>
                    </svg>
                    <input class="mx-2 border text-center w-11" type="text" value="{{ p.quantity }}">
                    <svg class="fill-current text-gray-600 w-3" viewBox="0 0 448 512">
                    <path d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"/>
                    </svg>
                </div>
                    <span class="text-center w-1/5 font-semibold text-xs md:text-sm">RM {{p.price}}</span>
                    <span class="text-center w-1/5 font-semibold text-xs md:text-sm">RM {{p.total_price}}</span>
                </div>
            {% empty %}
                <h1 class="font-semibold text-2xl text-center">No Order</h1>
            {% endfor %}
        </div>
        <div class="md:w-1/4 px-8 py-10">
            {% if cart.total_item %}
                <h1 class="font-semibold text-2xl border-b pb-8">Order Summary</h1>
                <div class="flex justify-between mt-10 mb-5">
                  <span class="font-semibold text-sm uppercase">Items {{ cart|length }}</span>
                  <span class="font-semibold text-sm">RM {{ cart.total_price }}</span>
                </div>
                <div class="border-t mt-8">
                    <div class="flex font-semibold justify-between py-6 text-sm uppercase">
                        <span>Total cost</span>
                        <span>RM {{ cart.total_price}}</span>
                    </div>
                    <span class="font-semibold text-sm uppercase">Pick up date</span>
                    <form action="{% url 'cart:checkout' %}" method="post">
                        {% csrf_token %}
                        <div date-rangepicker class="flex items-center pb-5">
                            <div class="relative">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                    <svg class="w-4 h-4 text-gray-500 border-gray-700" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                                    </svg>
                                </div>
                                <input name="start" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date start">
                            </div>
                            <span class="mx-4 text-gray-500">to</span>
                            <div class="relative">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                    <svg class="w-4 h-4 text-gray-500 border-gray-700" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
                                    </svg>
                                </div>
                                <input name="end" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date end">
                            </div>
                        </div>
                        <button class="bg-indigo-500 font-semibold hover:bg-indigo-600 py-3 text-sm text-white uppercase w-full">Checkout</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
    <a href="{% url 'shop:homepage' %}" class="flex font-semibold text-indigo-600 text-sm mt-10 pb-10">
        <svg class="fill-current mr-2 text-indigo-600 w-4" viewBox="0 0 448 512"><path d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"/></svg>
        Continue Shopping
    </a>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/datepicker.min.js"></script>

{% endblock %}

cart/templates/cart/order_pdf.html
<html>
    {% load static %}
    <head>
        <link href="{% static 'css/pdf.css' %}" rel="stylesheet">
    </head>
    <body>
<!--        <h1>@i@i Cookie</h1>-->
        <img src="{% static 'img/logo_low.png' %}" width="500" height="100" alt="AIAI Logo" />
        <p>
            Inovice no. #{{ order.order_id }}<br>
            <span class="secondary">
                Created {{ order.created | date:"M d, Y" }}
            </span>
        </p>
        <h3>Bill to</h3>
        <p>
            CHIN LINN KERN<br>
            kerncl@hhotmail.com<br>
            303-2-1 TAMAN GREEN FIELD,<br>
            11500 AIR ITAM, PULAU PINANG <br>
        </p>
        <h3>Item bought</h3>
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order %}
                    <tr class="row{% cycle '1' '2' %}">
                        <td>{{ item.product }}</td>
                        <td class="num">RM {{ item.price }}</td>
                        <td class="num">{{ item.quantity }}</td>
                        <td class="num">RM {{ item.total_price }}</td>
                    </tr>
                {% endfor %}
                <tr class="total">
                    <td colspan="3">Total</td>
                    <td class="num">RM {{ cart.total_price }}</td>
                </tr>
            </tbody>
        </table>
        <span class="pending">
            Pending Payment
        </span>
    </body>
</html>