aiai_cookie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>', views.cart_add, name='add'),
    path('remove/<int:product_id>', views.cart_remove, name='remove'),
    path('checkout/', views.checkout_page, name='checkout'),
    path('pdf/views/<int:order_id>/', views.cart_pdf_view, name='pdf'),
    path('pdf/<int:order_id>/', views.generate_order_pdf, name='generate_pdf'),
    path('', views.cartpage, name='cartpage'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    # path('', views.homepage, name='homepage'),
    path('', views.list_product_view, name='homepage'),
    path('product/<slug:slug>/', views.product_detail, name='product')
]

shop/models.py
import uuid

from django.db import models
from django.utils.html import mark_safe
from django.urls import reverse
# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products')

    class Meta:
        ordering = ['-updated', 'available','name']

    def image_tag(self):
        return mark_safe(f"<img src='{self.image.url}' width='150' height='150' />")

    image_tag.short_description = 'Image'

    def save(self, *args, **kwargs):
        if self.image.storage.exists(self.image.name):
            # if same name image submitted
            self.image.name = self.image.name + '_' + uuid.uuid4()[:8]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:product', args=[self.slug])

    def __str__(self):
        return self.name

shop/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=[(i, str(i)) for i in range(1,11)],
        coerce=int
    )

shop/views.py
from django.shortcuts import render

from .models import Product
from .forms import CartAddProductForm


# Create your views here.
def homepage(request):
    return render(request, 'base.html')


def list_product_view(request):
    p = Product.objects.filter(available=True)
    return render(request, 'shop/list.html', context={'products': p})


def product_detail(request, slug):
    p = Product.objects.get(slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/detail.html',
                  context={'product':p,
                           'cart_product_form': cart_product_form})

shop/templates/shop/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}@i @i Cookie{% endblock %}
{% block content %}
    <div class="flex flex-col items-center">
        <img class="rounded-t-lg pt-10" src="{{ product.image.url }}" alt="" />
        <h1 class="font-sans text-4xl font-bold capitalize text-orange-700 mt-20px py-7">{{ product.name }}</h1>
        <h5 class="text-justify">{{ product.description }}</h5>
        <h6 class="mb-2 text-2xl font-bold tracking-tight text-orange-800 capitalize">RM {{ product.price }}</h6>
        <form action="{% url 'cart:add' product.id %}" method="post">
            {{ cart_product_form.as_p }}
            {% csrf_token %}
            <br>
            <input type="hidden" value="Add to cart">
            <a onclick="this.parentNode.submit();" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-amber-500 rounded-lg hover:bg-amber-600 focus:ring-4 focus:outline-none focus:ring-blue-300 bg-blue-600 hover:bg-blue-700 focus:ring-blue-800">
                Add to Cart &nbsp;
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path d="M2.25 2.25a.75.75 0 000 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 00-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 000-1.5H5.378A2.25 2.25 0 017.5 15h11.218a.75.75 0 00.674-.421 60.358 60.358 0 002.96-7.228.75.75 0 00-.525-.965A60.864 60.864 0 005.68 4.509l-.232-.867A1.875 1.875 0 003.636 2.25H2.25zM3.75 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM16.5 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0z" />
                </svg>
            </a>
        </form>
    </div>
{% endblock %}

shop/templates/shop/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}@i @i Cookie{% endblock %}
{% block content %}
    <div class="flex flex-col gap-10 justify-start flex-warp md:flex-row px-12 py-5 my-5 mx-auto flex-wrap md:justify-start">
        {% for p in products %}
            <div class="hover:bg-orange-50 max-w-sm w-full bg-white border border-gray-200 rounded-lg shadow bg-orange-50 md:basis-1/3 lg:basis-1/3 items-stretch">
                <img class="rounded-t-lg" src="{{ p.image.url }}" alt="" />
                <div class="p-5">
                    <a href="{{ p.get_absolute_url }}">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-orange-600 capitalize">{{ p.name }}</h5>
                    </a>
                    <p class="mb-3 font-normal text-gray-700 text-gray-400 text-clip overflow-hidden">{{ p.description }}</p>
                    <h6 class="mb-2 text-2xl font-bold tracking-tight text-orange-800 capitalize">RM {{ p.price }}</h6>
                    <a href="{{ p.get_absolute_url }}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-amber-500 rounded-lg hover:bg-amber-600 focus:ring-4 focus:outline-none focus:ring-blue-300 bg-blue-600 hover:bg-blue-700 focus:ring-blue-800">
                        Add to Cart &nbsp;
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                            <path d="M2.25 2.25a.75.75 0 000 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 00-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 000-1.5H5.378A2.25 2.25 0 017.5 15h11.218a.75.75 0 00.674-.421 60.358 60.358 0 002.96-7.228.75.75 0 00-.525-.965A60.864 60.864 0 005.68 4.509l-.232-.867A1.875 1.875 0 003.636 2.25H2.25zM3.75 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM16.5 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0z" />
                        </svg>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}